apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: webserver
    tier: frontend
    environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx