apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysqlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      name: mysql_pod
      labels:
        app: mysqlapp
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: my-pvc