apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: webserver
    tier: frontend
    environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx

# #kubectl expose deployment nginx --type=NodePort --port 80 --target-port 80 --name testsvc