apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 801
      targetPort: 80

#kubectl expose deployment nginx-deployment --type=NodePort --port 80 --target-port 80 --name testsvc