apiVersion: v1
kind: Pod
metadata:
  name: pod-mount
spec:
  containers:
    - name: nginx-container
      image: nginx:1.20
      volumeMounts:
        - name: my-volume
          mountPath: /var/www/html
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc